optim:
    type: adam
    lr: 0.0001
loss_fn:
    type: squared
function_class: 
    type: decision tree
b_size: 32
seq_len: !curriculum
    start: 26
    stop: 101
    step_size: 5
    step_len: 2000
x_dim: !curriculum
    start: 5
    stop: 20
    step_size: 1
    step_len: 2000
x_dist:
    type: normal
steps: 500000
log_freq: 100
checkpoint_freq: 5000
model: *std_llama
baseline_models: [*knn_3, *xgboost, *decision_tree]
