optim:
    type: adam
    lr: 0.0001
loss_fn:
    type: squared
function_class: 
    type: 2 layer mlp regression
    hidden_dimension: 40
b_size: 32
seq_len: !curriculum
    start: 11
    stop: 42
    step_size: 2
    step_len: 5000
x_dim: !curriculum
    start: 5
    stop: 20
    step_size: 1
    step_len: 7500
x_dist:
    type: normal
steps: 500000
log_freq: 100
checkpoint_freq: 5000
model: *std_gpt2
baseline_models: [*knn_3, *least_squares]
