defs:
    block: &llammba_block
        - rms norm
        - llama attention no rope
        - residual
        - mamba block
        - residual

    block: &llammba_block_with_rope
        - rms norm
        - llama attention
        - residual
        - mamba block
        - residual

    block: &llama_block
        - rms norm
        - llama attention
        - residual
        - rms norm
        - llama mlp
        - residual

    base: &hybrid_base_config
        type: hybrid
        n_positions: 101
        n_embd: 64
        n_head: 4

model: &llama_with_rope_replaced
    <<: *hybrid_base_config
    module_names:
        - residual
        - mamba block
        - residual

        - *llama_block
        - *llama_block
        - *llama_block

        - *llama_block
        - *llama_block
        - *llama_block

        - rms norm

model: &llama_with_ffn_and_rope_replaced
    <<: *hybrid_base_config
    module_names:
        - residual
        - mamba block
        - residual
        - *llammba_block
        - *llammba_block
        - *llammba_block

        - *llammba_block
        - *llammba_block
        - *llammba_block

        - rms norm

model: &llama_with_ffn_replaced
    <<: *hybrid_base_config
    module_names:
        - residual

        - *llammba_block_with_rope
        - *llammba_block_with_rope
        - *llammba_block_with_rope

        - *llammba_block_with_rope
        - *llammba_block_with_rope
        - *llammba_block_with_rope

        - rms norm
