model: &std_gpt2
    type: gpt2
    n_positions: 101
    n_layer: 12
    n_embd: 256
    n_head: 8

model: &std_llama
    type: llama
    n_positions: 101
    n_layer: 12
    n_embd: 256
    n_head: 8

model: &knn_3
    type: knn
    n_neighbors: 3

model: &least_squares
    type: least squares

model: &xgboost
    type: xgboost

model: &averaging
    type: averaging

model: &decision_tree_4
    type: decision_tree
    max_depth: 4

model: &decision_tree
    type: decision_tree
    max_depth: None


model: &mlp
    type: mlp
    dimensions: [20, 100, 1]
    opt_alg_name: adam
    batch_size: 100
    lr: 5e-3
    num_steps: 100

model: &lasso
    type: lasso

model: &lasso_set
  - <<: *least_squares
  - <<: *averaging
  - <<: *lasso
    alpha: 0.0001
  - <<: *lasso
    alpha: 0.001
  - <<: *lasso
    alpha: 0.01
  - <<: *lasso
    alpha: 0.1
  - <<: *lasso
    alpha: 1

model: &zero
    type: zero
