optim:
    type: adam
    lr: 0.0001
loss_fn:
    type: squared
function_class: 
    type: sparse linear regression
b_size: 32
seq_len: 42
x_dim: 20
x_dist:
    type: normal
steps: 1000000
log_freq: 100
checkpoint_freq: 5000
model: *lora_std_llama
baseline_models: [*least_squares]
