defs: 
    shared: &task_base_config
        optim:
            type: adam
            lr: 0.0001
        loss_fn:
            type: squared
        b_size: 64
        x_dist:
            type: normal
        x_dim: !curriculum
            start: 5
            stop: 20
            step_size: 1
            step_len: 2000
    
    seq_len: &short_sequence_curriculum !curriculum
        start: 11
        stop: 41
        step_size: 2
        step_len: 2000
    
    seq_len: &long_sequence_curriculum !curriculum
        start: 26
        stop: 101
        step_size: 5
        step_len: 2000

task: &decision_tree_regression
    <<: *task_base_config
    seq_len: *long_sequence_curriculum
    function_class: 
        type: decision tree
        depth: 4
    # baseline_models: [*knn_3, *xgboost, *decision_tree, *decision_tree_4]

task: &linear_regression
    <<: *task_base_config
    seq_len: *short_sequence_curriculum
    function_class:
        type: linear regression
    # baseline_models: [*least_squares, *knn_3, *averaging]

task: &mlp_regression
    <<: *task_base_config
    seq_len: *long_sequence_curriculum
    function_class: 
        type: 2 layer mlp regression
        hidden_dimension: 100
    # baseline_models: [*knn_3, *least_squares, *mlp]

task: &sparse_linear_regression
    <<: *task_base_config
    seq_len: *short_sequence_curriculum
    function_class: 
        type: sparse linear regression
        sparsity: 3
    # baseline_models: *lasso_set

task: &sparse_parity_regression
    <<: *task_base_config
    x_dim: 10
    x_dist:
        type: sparse
    optim:
        type: adam
        lr: 0.0004
    function_class: 
        type: sparse parity regression
        k: 2
    seq_len: 140
    # baseline_models: [] # TODO: provide at least *one* baseline here

task: &retrieval
    <<: *task_base_config
    x_dim: 20
    optim:
        type: adam
        lr: 0.0002
    seq_len: 64
    function_class: 
        type: retrieval
    y_dim: 20
    predict_last: True
    # baseline_models: [*retrieval_dict]

task: &chebyshev_kernel_linear_regression
    <<: *task_base_config
    x_dim: 1
    x_dist:
        type: uniform
    seq_len: *short_sequence_curriculum
    function_class: 
        type: chebyshev kernel linear regression
        lowest_degree: 3
        highest_degree: 11

task: &chebyshev_shared_roots_regression
    <<: *task_base_config
    x_dim: 1
    x_dist:
        type: uniform
    seq_len: *short_sequence_curriculum
    function_class:
        type: chebyshev shared roots
        degree: 5
        perturbation: 0.2
