name: test-function-classes

on:
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ["3.10"]
        steps:
            - uses: actions/checkout@v4

            - name: Setup Miniconda
              uses: conda-incubator/setup-miniconda@v3.0.3
              with:
                  # Specific version of Conda to install after miniconda is located 
                  #    or installed. See https://anaconda.org/anaconda/conda for 
                  #    available "conda" versions.
                  # conda-version: # something, this may be useful later
                  # Environment.yml to create an environment.
                  environment-file: environment.yaml
                  # Environment name (or path) to activate on all shells. Default 
                  #    is `test` which will be created in `$CONDA/envs/test`. If the 
                  #    environment does not exist, it will be created and activated. 
                  #    If `environment-file` is used and you want that to be the 
                  #    environment used, you need to explicitely provide the name of 
                  #    that environment on `activate-environment`.
                  activate-environment: in-context-learning
                  # Exact version of a Python version to use on "activate-environment". 
                  #    If provided, this will be installed before the "environment-file". 
                  #    See https://anaconda.org/anaconda/python for available "python" versions.
                  python-version: ${{ matrix.python-version }}

            - name: Run function class
              run: |
                # Extract all function classes
                START_FROM_LINE=$(grep -n "FUNCTION_CLASSES = {" src/function_classes/__init__.py  | cut -f1 -d:)
                END_AT_LINE=$(grep -n "}" src/function_classes/__init__.py  | cut -f1 -d:)
                FUNC_CLASSES=$(tail -n+$(($START+1)) src/function_classes/__init__.py  | head -n$(($END-$START-1)) | cut -d\" -f2)

                while read line; do 
                    bash .github/prep_func_test_yaml.sh \""$line"\"
                    conda run -n in-context-learning python src/ -c conf/test.yml
                done <<< "$FUNC_CLASSES"
